/**
 * UOR Receipt Registry — Canonical store for WASM-enriched receipts.
 *
 * Every receipt generated by the Oracle passes through the WASM Rust ring
 * engine (uor-foundation crate) to produce an algebraic signature.
 * This registry stores source objects + enriched receipts for cross-page lookup.
 */

import * as bridge from "@/lib/wasm/uor-bridge";
import { singleProofHash, type SingleProofResult } from "@/lib/uor-canonical";

// ── Enriched Receipt (WASM-anchored) ───────────────────────────────────────

export interface EnrichedReceipt {
  /** CIDv1 / dag-json / sha2-256 / base32lower */
  cid: string;
  /** urn:uor:derivation:sha256:{hex64} */
  derivationId: string;
  /** Braille glyph bijection */
  glyph: string;
  /** Content-addressed IPv6 ULA */
  ipv6: string;
  /** Raw hex of SHA-256 */
  hashHex: string;
  /** URDNA2015 canonical N-Quads */
  nquads: string;

  // ── WASM Ring Algebraic Signature ──
  /** First byte of the SHA-256 hash — the ring element */
  ringByte: number;
  /** Ring partition classification (e.g. "Irreducible", "PrimePower") */
  ringPartition: string;
  /** Prime factorization of the ring byte */
  ringFactors: number[];
  /** Whether the critical identity (x ⊕ ¬x = 0xFF) holds for this byte */
  ringCriticalIdentity: boolean;
  /** Popcount (Hamming weight) of the ring byte */
  ringPopcount: number;
  /** Basis elements of the ring byte */
  ringBasis: number[];
  /** "wasm" or "typescript" — which engine computed the ring data */
  engine: "wasm" | "typescript";
  /** Crate version if WASM, null if TS fallback */
  crateVersion: string | null;
}

export interface RegistryEntry {
  /** The original JSON-LD source object */
  source: unknown;
  /** The WASM-enriched receipt */
  receipt: EnrichedReceipt;
  /** Timestamp of creation */
  createdAt: number;
}

// ── Global Registry ────────────────────────────────────────────────────────

const registry = new Map<string, RegistryEntry>();

/**
 * Enrich a SingleProofResult with WASM ring algebraic data.
 * Every byte passes through the Rust uor-foundation ring engine.
 */
export function enrichWithWasm(proof: SingleProofResult): Omit<EnrichedReceipt, "nquads"> & { nquads: string } {
  const ringByte = proof.hashBytes[0];

  return {
    cid: proof.cid,
    derivationId: proof.derivationId,
    glyph: proof.uorAddress["u:glyph"],
    ipv6: proof.ipv6Address["u:ipv6"],
    hashHex: proof.hashHex,
    nquads: proof.nquads,

    // WASM ring signature — every call goes through bridge → WASM if loaded
    ringByte,
    ringPartition: bridge.classifyByte(ringByte),
    ringFactors: bridge.factorize(ringByte),
    ringCriticalIdentity: bridge.verifyCriticalIdentity(ringByte),
    ringPopcount: bridge.bytePopcount(ringByte),
    ringBasis: bridge.byteBasis(ringByte),
    engine: bridge.engineType(),
    crateVersion: bridge.crateVersion(),
  };
}

/**
 * Compute a WASM-anchored receipt for any object and register it.
 * Pipeline: obj → URDNA2015 → SHA-256 → CID + ring signature.
 */
export async function computeAndRegister(source: unknown): Promise<EnrichedReceipt> {
  const proof = await singleProofHash(source);
  const enriched = enrichWithWasm(proof);

  registry.set(enriched.cid, {
    source,
    receipt: enriched,
    createdAt: Date.now(),
  });

  // Also index by derivationId for lookup flexibility
  registry.set(enriched.derivationId, {
    source,
    receipt: enriched,
    createdAt: Date.now(),
  });

  return enriched;
}

/** Look up a registry entry by CID or derivation ID */
export function lookupReceipt(key: string): RegistryEntry | undefined {
  return registry.get(key);
}

/** Get all registered entries */
export function allEntries(): RegistryEntry[] {
  // Deduplicate (each entry is stored under both CID and derivationId)
  const seen = new Set<string>();
  const result: RegistryEntry[] = [];
  for (const entry of registry.values()) {
    if (!seen.has(entry.receipt.cid)) {
      seen.add(entry.receipt.cid);
      result.push(entry);
    }
  }
  return result;
}

/** Clear the registry */
export function clearRegistry(): void {
  registry.clear();
}

/** Registry size (unique entries) */
export function registrySize(): number {
  return allEntries().length;
}
