/**
 * UOR Foundation v2.0.0 — kernel::op
 *
 * 10 primitive operations, dihedral symmetry, and the critical identity.
 *
 * @see spec/src/namespaces/op.rs
 * @namespace op/
 */

import type { PrimitiveOp, GeometricCharacter } from "../enums";
import type { Datum } from "./schema";

/**
 * Operation — abstract base for all ring operations.
 */
export interface Operation {
  /** Canonical operation name. */
  name(): PrimitiveOp;
  /** Geometric character classification. */
  geometricCharacter(): GeometricCharacter;
  /** Whether this operation is its own inverse (f∘f = id). */
  isInvolution(): boolean;
  /** Arity: 1 for unary, 2 for binary. */
  arity(): number;
}

/**
 * UnaryOp — operation on a single ring element.
 *
 * @disjoint BinaryOp
 */
export interface UnaryOp extends Operation {
  /** Apply to a single datum. */
  apply(x: Datum): Datum;
}

/**
 * BinaryOp — operation on two ring elements.
 *
 * @disjoint UnaryOp
 */
export interface BinaryOp extends Operation {
  /** Apply to two datums. */
  apply(x: Datum, y: Datum): Datum;
}

/**
 * Involution — a unary operation where f(f(x)) = x for all x.
 * neg and bnot are both involutions.
 */
export interface Involution extends UnaryOp {
  /** Always returns true. */
  isInvolution(): true;
}

/**
 * Identity — the identity operation (f(x) = x for all x).
 */
export interface IdentityOp extends UnaryOp {
  /** Always "Identity". */
  name(): "Neg"; // identity is expressed as neg∘neg
  isInvolution(): true;
}

/**
 * Group — abstract algebraic group.
 */
export interface Group {
  /** Group order. */
  order(): bigint;
  /** Generator elements. */
  generators(): PrimitiveOp[];
}

/**
 * DihedralGroup — D_{2^n} symmetry group generated by (neg, bnot).
 *
 * Presentation: ⟨r, s | r^{2^n} = s² = e, srs = r⁻¹⟩
 * where r = succ (rotation) and s = neg (reflection).
 */
export interface DihedralGroup extends Group {
  /** Always [Neg, Bnot]. */
  generators(): ["Neg", "Bnot"];
  /** Dihedral presentation string. */
  presentation(): string;
  /** Quantum level. */
  quantum(): number;
}

// ── Named Individuals ──────────────────────────────────────────────────────

/** critical_identity — the mathematical anchor: neg(bnot(x)) = succ(x). */
export const CRITICAL_IDENTITY = {
  "@id": "op:critical_identity",
  forAll: "x ∈ R_n",
  lhs: "Succ" as PrimitiveOp,
  rhs: ["Neg", "Bnot"] as [PrimitiveOp, PrimitiveOp],
  equation: "neg(bnot(x)) = succ(x)",
} as const;

/** d2n — the dihedral group generated by neg and bnot. */
export const D2N = {
  "@id": "op:d2n",
  generatedBy: ["Neg", "Bnot"] as [PrimitiveOp, PrimitiveOp],
  presentation: "⟨r, s | r^{2^n} = s² = e, srs = r⁻¹⟩",
} as const;

// ── Geometric Character Mapping (canonical) ────────────────────────────────

/** Canonical mapping from PrimitiveOp to GeometricCharacter. */
export const OP_GEOMETRY: Record<PrimitiveOp, GeometricCharacter> = {
  Neg:  "RingReflection",
  Bnot: "HypercubeReflection",
  Succ: "Rotation",
  Pred: "RotationInverse",
  Add:  "Translation",
  Sub:  "Translation",
  Mul:  "Scaling",
  Xor:  "HypercubeTranslation",
  And:  "HypercubeProjection",
  Or:   "HypercubeJoin",
};
